export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST'
export const  CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const  CREATE_COMMENT_FAIL = ' CREATE_COMMENT_FAIL'
export const  CREATE_COMMENT_RESET = ' CREATE_COMMENT_RESET'


export const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST'
export const  EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS'
export const  EDIT_COMMENT_FAIL = ' EDIT_COMMENT_FAIL'


export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'
export const  DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const  DELETE_COMMENT_FAIL = ' DELETE_COMMENT_FAIL'