export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST'
export const  CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const  CREATE_COMMENT_FAIL = ' CREATE_COMMENT_FAIL'
export const  CREATE_COMMENT_RESET = ' CREATE_COMMENT_RESET'


export const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST'
export const  EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS'
export const  EDIT_COMMENT_FAIL = ' EDIT_COMMENT_FAIL'
export const EDIT_COMMENT_RESET = 'EDIT_COMMENT_RESET'

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'
export const  DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const  DELETE_COMMENT_FAIL = ' DELETE_COMMENT_FAIL'
export const DELETE_COMMENT_RESET = 'DELETE_COMMENT_RESET'


export const LIKE_COMMENT_REQUEST = 'LIKE_COMMENT_REQUEST'
export const  LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS'
export const  LIKE_COMMENT_FAIL = ' LIKE_COMMENT_FAIL'
export const LIKE_COMMENT_RESET = 'Like_COMMENT_RESET'


export const REPLY_COMMENT_REQUEST = 'REPLY_COMMENT_REQUEST'
export const  REPLY_COMMENT_SUCCESS = 'REPLY_COMMENT_SUCCESS'
export const  REPLY_COMMENT_FAIL = ' REPLY_COMMENT_FAIL'
export const REPLY_COMMENT_RESET = 'REPLY_COMMENT_RESET'

