export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const  CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const  CREATE_POST_FAIL = ' CREATE_POST_FAIL'
export const  CREATE_POST_RESET = ' CREATE_POST_RESET'

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const  UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const  UPDATE_POST_FAIL = ' UPDATE_POST_FAIL'
export const  UPDATE_POST_RESET = ' UPDATE_POST_RESET'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const  DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const  DELETE_POST_FAIL = ' DELETE_POST_FAIL'
export const DELETE_POST_RESET = 'DELETE_POST_RESET'


export const GET_ALLPOSTS_REQUEST = 'GET_ALLPOSTS_REQUEST'
export const  GET_ALLPOSTS_SUCCESS = 'GET_ALLPOSTS_SUCCESS'
export const  GET_ALLPOSTS_FAIL = ' GET_ALLPOSTS_FAIL'


export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST'
export const  LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const  LIKE_POST_FAIL = ' LIKE_POST_FAIL'
