export const GET_ALLPOSTS_REQUEST = 'GET_ALLPOSTS_REQUEST'
export const  GET_ALLPOSTS_SUCCESS = 'GET_ALLPOSTS_SUCCESS'
export const  GET_ALLPOSTS_FAIL = ' GET_ALLPOSTS_FAIL'


export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST'
export const  LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const  LIKE_POST_FAIL = ' LIKE_POST_FAIL'
