export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'


export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'


export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'


export const USER_FRIENDS_REQUEST = 'USER_FRIENDS_REQUEST'
export const USER_FRIENDS_SUCCESS = 'USER_FRIENDS_SUCCESS'
export const USER_FRIENDS_FAIL = 'USER_FRIENDS_FAIL'
export const USER_FRIENDS_RESET = 'USER_FRIENDS_RESET'


export const RECOMMENDED_FRIENDS_REQUEST = 'RECOMMENDED_FRIENDS_REQUEST'
export const RECOMMENDED_FRIENDS_SUCCESS = 'RECOMMENDED_FRIENDS_SUCCESS'
export const RECOMMENDED_FRIENDS_FAIL = 'RECOMMENDED_FRIENDS_FAIL'
export const RECOMMENDED_FRIENDS_RESET = 'RECOMMENDED_FRIENDS_RESET'



export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST'
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS'
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL'
export const FOLLOW_USER_RESET = 'FOLLOW_USER_RESET'


export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST'
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS'
export const UNFOLLOW_USER_FAIL = 'UNFOLLOW_USER_FAIL'
export const UNFOLLOW_USER_RESET = 'UNFOLLOW_USER_RESET'


